services:
  Homeapp\AuditBundle\Audit:
    public: true
    autowire: true
  Homeapp\AuditBundle\StorageInterface: '@Homeapp\AuditBundle\DatabaseStorage'
  Homeapp\AuditBundle\DatabaseStorage:
    public: false
    autowire: true
  Homeapp\AuditBundle\IdentifierExtractor:
    autowire: true
  Homeapp\AuditBundle\ActorInfoFetcherInterface:
  Homeapp\AuditBundle\ChangeSet:
    autowire: true
  Homeapp\AuditBundle\ChangeSetInterface: '@Homeapp\AuditBundle\ChangeSet'
  Homeapp\AuditBundle\RequestIdentifierInterface: '@Homeapp\AuditBundle\RequestIdentifier'
  Homeapp\AuditBundle\RequestIdentifier:
  Homeapp\AuditBundle\Auditable:
  Homeapp\AuditBundle\EventListener\DatabaseActivitySubscriber:
    autowire: true
    tags:
      - { name: 'doctrine.event_subscriber' }